name: CI

on:
  workflow_call:
    inputs:
      # pass in environment through manual trigger, if not passed in, default to 'dev'
      environment:
        required: true
        type: string
      # working-directory is added to accommodate monorepo.  For multi repo, defaults to '.', current directory
      test-aja:
        required: true
        type: string

jobs:
  build-push-deploy:
    runs-on: ktbs-infra-k8s-runner

    steps:
      - name: Checking out repository
        uses: actions/checkout@v2

      - name: Test Doang
        run: |-
          echo ${{ inputs.test-aja }}
          echo ${{ inputs.env }}
